### ISSUE TITLE
Program To Extract zip Files

### ISSUE THREAD

**Issue by TechnicalGeeks20** [TechnicalGeeks20/PyThonPrograms#2]
Requirements 👍 
1. Program should be in Python
2. Program should first ask for Zip file Name as Input (Includes " Directory or path ") .
3. Program should extract zip file .
4. zip file  should be  extracted to a particular folder of our choice  .

Output 👍 
1 . Enter zip file name with directory : myzipfile.zip
2 . Enter Folder Name where files will be extracted

**Comment by Rohan1904** [comment]
Hey ! @TechnicalGeeks20  I would Like to contribute ? Should I proceed .

**Comment by TechnicalGeeks20** [comment]
Ofcource You can Proceed Good Luck . 💯
